// fsScript.ts — Filesystem Script Generator + Schema Validation
// Used by C3.2 (generate-script) and C3.3 (paste-import + snapshots)

export interface FsTreeNode {
  path: string
  type: 'dir' | 'file'
  size: number | null
  mtime: string
}

export interface FsTreeDoc {
  schema: 'bi-ro.fstree.v1'
  root: string
  host: string
  generated_at: string
  max_depth: number
  nodes: FsTreeNode[]
}

// ── Script generators ──────────────────────────────────────────────────────────

/**
 * Generate a self-contained bash script that walks `root` up to `maxDepth`
 * and emits a bi-ro.fstree.v1 JSON document to stdout.
 * Values are baked in — the user just runs the script on their server.
 */
export function generateBashScript(root: string, maxDepth: number, host: string): string {
  // Escape single-quotes in user-supplied strings for embedding in the heredoc
  const safeRoot = root.replace(/'/g, "'\\''")
  const safeHost = host.replace(/'/g, "'\\''")

  return `#!/usr/bin/env bash
set -euo pipefail

# bi-ro.fstree.v1 — generated by BI-Ro filesystem scanner
ROOT='${safeRoot}'
MAX_DEPTH=${maxDepth}
HOST='${safeHost}'
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

python3 -c "
import os, sys, json
from datetime import datetime, timezone

root = sys.argv[1]
max_depth = int(sys.argv[2])
host = sys.argv[3]
generated_at = sys.argv[4]
nodes = []
root_depth = root.rstrip('/').count('/')

for dirpath, dirnames, filenames in os.walk(root):
    depth = dirpath.rstrip('/').count('/') - root_depth
    if depth > max_depth:
        dirnames[:] = []
        continue
    if depth > 0 or dirpath != root:
        s = os.stat(dirpath)
        nodes.append({
            'path': dirpath,
            'type': 'dir',
            'size': None,
            'mtime': datetime.fromtimestamp(s.st_mtime, tz=timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
        })
    for fname in sorted(filenames):
        fpath = os.path.join(dirpath, fname)
        try:
            s = os.stat(fpath)
            nodes.append({
                'path': fpath,
                'type': 'file',
                'size': s.st_size,
                'mtime': datetime.fromtimestamp(s.st_mtime, tz=timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
            })
        except OSError:
            pass

print(json.dumps({
    'schema': 'bi-ro.fstree.v1',
    'root': root,
    'host': host,
    'generated_at': generated_at,
    'max_depth': max_depth,
    'nodes': nodes
}, indent=2))
" "\$ROOT" "\$MAX_DEPTH" "\$HOST" "\$GENERATED_AT"
`
}

/**
 * Generate a self-contained PowerShell script that walks `root` up to `maxDepth`
 * and emits a bi-ro.fstree.v1 JSON document to stdout.
 * Values are baked in — the user just runs the script on their Windows server.
 */
export function generatePs1Script(root: string, maxDepth: number, host: string): string {
  // Escape double-quotes for PowerShell string embedding
  const safeRoot = root.replace(/"/g, '`"')
  const safeHost = host.replace(/"/g, '`"')

  return `# bi-ro.fstree.v1 — generated by BI-Ro filesystem scanner
$Root = "${safeRoot}"
$MaxDepth = ${maxDepth}
$HostName = "${safeHost}"
$GeneratedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$nodes = @()

# Walk the tree using Get-ChildItem with -Recurse -Depth
$items = Get-ChildItem -LiteralPath $Root -Recurse -Depth $MaxDepth -ErrorAction SilentlyContinue -Force

foreach ($item in $items) {
    if ($item.PSIsContainer) {
        $nodes += [PSCustomObject]@{
            path  = $item.FullName
            type  = "dir"
            size  = $null
            mtime = $item.LastWriteTimeUtc.ToString("yyyy-MM-ddTHH:mm:ssZ")
        }
    } else {
        $nodes += [PSCustomObject]@{
            path  = $item.FullName
            type  = "file"
            size  = $item.Length
            mtime = $item.LastWriteTimeUtc.ToString("yyyy-MM-ddTHH:mm:ssZ")
        }
    }
}

$doc = [PSCustomObject]@{
    schema       = "bi-ro.fstree.v1"
    root         = $Root
    host         = $HostName
    generated_at = $GeneratedAt
    max_depth    = $MaxDepth
    nodes        = $nodes
}

$doc | ConvertTo-Json -Depth 5
`
}

// ── Schema validation ──────────────────────────────────────────────────────────

/**
 * Validate a parsed JSON value against the bi-ro.fstree.v1 schema.
 * Returns { valid: true } on success, { valid: false, error: string } on failure.
 */
export function validateFsTreeSchema(data: unknown): { valid: boolean; error?: string } {
  if (typeof data !== 'object' || data === null || Array.isArray(data)) {
    return { valid: false, error: 'Document must be a JSON object' }
  }

  const doc = data as Record<string, unknown>

  if (doc['schema'] !== 'bi-ro.fstree.v1') {
    return { valid: false, error: `schema must be "bi-ro.fstree.v1", got "${String(doc['schema'])}"` }
  }

  if (typeof doc['root'] !== 'string' || !doc['root']) {
    return { valid: false, error: 'root must be a non-empty string' }
  }

  if (typeof doc['host'] !== 'string' || !doc['host']) {
    return { valid: false, error: 'host must be a non-empty string' }
  }

  if (typeof doc['generated_at'] !== 'string' || !doc['generated_at']) {
    return { valid: false, error: 'generated_at must be a non-empty string' }
  }

  if (
    typeof doc['max_depth'] !== 'number' ||
    !Number.isInteger(doc['max_depth']) ||
    doc['max_depth'] < 1 ||
    doc['max_depth'] > 20
  ) {
    return { valid: false, error: 'max_depth must be an integer between 1 and 20' }
  }

  if (!Array.isArray(doc['nodes'])) {
    return { valid: false, error: 'nodes must be an array' }
  }

  for (let i = 0; i < (doc['nodes'] as unknown[]).length; i++) {
    const node = (doc['nodes'] as unknown[])[i]
    if (typeof node !== 'object' || node === null || Array.isArray(node)) {
      return { valid: false, error: `nodes[${i}] must be an object` }
    }
    const n = node as Record<string, unknown>

    if (typeof n['path'] !== 'string' || !n['path']) {
      return { valid: false, error: `nodes[${i}].path must be a non-empty string` }
    }
    if (n['type'] !== 'dir' && n['type'] !== 'file') {
      return { valid: false, error: `nodes[${i}].type must be "dir" or "file"` }
    }
    if (n['size'] !== null && typeof n['size'] !== 'number') {
      return { valid: false, error: `nodes[${i}].size must be a number or null` }
    }
    if (typeof n['mtime'] !== 'string' || !n['mtime']) {
      return { valid: false, error: `nodes[${i}].mtime must be a non-empty string` }
    }
  }

  return { valid: true }
}
